/* Axel settings, generated by configure */
#ifndef _REENTRANT
#define _REENTRANT
#endif // !_REENTRANT
#ifndef _THREAD_SAFE
#define _THREAD_SAFE
#endif // !_THREAD_SAFE
#ifndef ETCDIR
#define ETCDIR "/usr/local/etc"
#endif // !ETCDIR
#ifndef LOCALE
#define LOCALE "/usr/local/share/locale"
#endif // !LOCALE
#ifndef ARCH
#define ARCH "Darwin"
#endif // !ARCH

#ifndef NOGETOPTLONG
#define NOGETOPTLONG
#endif // !NOGETOPTLONG
#ifndef DARWIN
#define DARWIN
#endif // !DARWIN
