BaseView = BaseView or {}
-- 用于视图事件
--[[
--视图入场前调用
BaseView.WILL_VIEW_ENTER = "BaseView:WILL_VIEW_ENTER"
--视图出场前调用
BaseView.WILL_VIEW_EXIT = "BaseView:WILL_VIEW_EXIT"--]]

--视图资源加载完成后调用（只有收到这条消息后，视图才会执行进入相关代码）
BaseView.LOAD_VIEW_ASYNC_FINISHED = "BaseView:LOAD_VIEW_ASYNC_FINISHED"
--视图资源卸载完成后调用（只有收到这条消息后，视图才会执行退出相关代码）
BaseView.UNLOAD_VIEW_ASYNC_FINISHED = "BaseView:UNLOAD_VIEW_ASYNC_FINISHED"
--视图进入后播放动画完成后调用（只有收到这条消息后，视图才会真正执行进入）
BaseView.ENTER_VIEW_ASYNC_FINISHED = "BaseView.ENTER_VIEW_ASYNC_FINISHED"
--视图退出前播放动画完成后调用（只有收到这条消息后，视图才会真正执行退出）
BaseView.EXIT_VIEW_ASYNC_FINISHED = "BaseView.EXIT_VIEW_ASYNC_FINISHED"

--命令
GAME_COMMAMD = GAME_COMMAMD or {}
--启动命令
GAME_COMMAMD.START_UP               = "START_UP"
GAME_COMMAMD.LOAD_VIEW				= "LOAD_VIEW"			--装载视图
GAME_COMMAMD.UNLOAD_VIEW			= "UNLOAD_VIEW"			--卸载视图
--视图相关命令
GAME_COMMAMD.PUSH_VIEW				= "PUSH_VIEW"			--视图压栈
GAME_COMMAMD.POP_VIEW				= "POP_VIEW"			--视图出栈
--更新命令
GAME_COMMAMD.UPDATE_USER_SCORE		= "UPDATE_USER_SCORE"	--更新用户金币
GAME_COMMAMD.UPDATE_INSURE_SCORE	= "UPDATE_INSURE_SCORE"	--更新银行金币
GAME_COMMAMD.UPDATE_USER_FACE 		= "UPDATE_USER_FACE"	--更新用户头像
GAME_COMMAMD.UPDATE_GONGGAO 		= "UPDATE_GONGGAO"		--更新公告
GAME_COMMAMD.UPDATE_PLAZA_GAME_LIST = "UPDATE_PLAZA_GAME_LIST"	--更新游戏列表
GAME_COMMAMD.UPDATE_BANK_INFO 		= "UPDATE_BANK_INFO"	--更新银行信息
--音乐相关
GAME_COMMAMD.PLAY_EFFECT 			= "PLAY_EFFECT"			--音效播放
GAME_COMMAMD.PLAY_ONE_EFFECT 		= "PLAY_ONE_EFFECT"		--有且仅有一次 播放音效
--其他命令
--大厅广告加载结果
GAME_COMMAMD.HALL_GONGGAO_RESULT = "HALL_GONGGAO_RESULT"	 --大厅公告加载结果

--视图列表
VIEW_LIST = VIEW_LIST or {}
VIEW_LIST.WELLCOME_SCENE = "WELLCOME_SCENE"
VIEW_LIST.LOGON_SCENE = "LOGON_SCENE"
VIEW_LIST.CLIENT_SCENE = "CLIENT_SCENE"
VIEW_LIST.ROOM_TABLE_LAYER = "ROOM_TABLE_LAYER"
VIEW_LIST.ROOM_LIST_LAYER = "ROOM_LIST_LAYER"
VIEW_LIST.GONGGAO_LAYER = "GONGGAO_LAYER"
VIEW_LIST.VIP_LAYER = "VIP_LAYER"
VIEW_LIST.GONGGAO_IOS_LAYER = "GONGGAO_IOS_LAYER"
VIEW_LIST.PERSON_LAYER = "PERSON_LAYER"
VIEW_LIST.POPWAIT_LAYER = "POPWAIT_LAYER"
VIEW_LIST.SELECT_SYSTEM_HEAD_LAYER = "SELECT_SYSTEM_HEAD_LAYER"
VIEW_LIST.QUERY_DIALOG_LAYER = "QUERY_DIALOG_LAYER"
VIEW_LIST.SHARE_LAYER = "SHARE_LAYER"
VIEW_LIST.GAME_LAYER = "GAME_LAYER"
VIEW_LIST.ACTIVITY_LAYER = "ACTIVITY_LAYER"
VIEW_LIST.ACTIVITY_IOS_LAYER = "ACTIVITY_IOS_LAYER"
VIEW_LIST.MODIFY_ACCOUNT_PASS_LAYER = "MODIFY_ACCOUNT_PASS_LAYER"
VIEW_LIST.MODIFY_BANK_PASS_LAYER = "MODIFY_BANK_PASS_LAYER"
VIEW_LIST.TASKLAYER = "TASK_LAYER"
VIEW_LIST.BANK_LAYER = "BANK_LAYER"
VIEW_LIST.BANK_OPEN_LAYER = "BANK_OPEN_LAYER"
VIEW_LIST.GAME_WAIT_LAYER = "GAME_WAIT_LAYER"
VIEW_LIST.SHOP_LAYER = "SHOP_LAYER"
VIEW_LIST.SHOP_APPSTORE_LAYER = "SHOP_APPSTORE_LAYER"
VIEW_LIST.SETTING_LAYER = "SETTING_LAYER"
VIEW_LIST.EARN_LAYER = "EARN_LAYER"
VIEW_LIST.EARN_MONEY = "EARN_MONEY"
VIEW_LIST.VISITOR_BIND_LAYER = "VISITOR_BIND_LAYER"
VIEW_LIST.AGENT_RECHARGE_LAYER = "AGENT_RECHARGE_LAYER"
VIEW_LIST.REGISTER_AGREATMENT = "REGISTER_AGREATMENT"
VIEW_LIST.ACCOUNT_REGISTER_LAYER = "ACCOUNT_REGISTER_LAYER"
VIEW_LIST.SHOW_POP_TIPS = "SHOW_POP_TIPS"
VIEW_LIST.SHOP_SHENGQING_DAILI = "SHOP_SHENGQING_DAILI"
VIEW_LIST.SHOP_SHENGQING_DAILI_COMFIRM = "SHOP_SHENGQING_DAILI_COMFIRM"
VIEW_LIST.SHOP_TOUSU_DAILI = "SHOP_TOUSU_DAILI"
VIEW_LIST.AGENT_AGREATMENT = "AGENT_AGREATMENT"
VIEW_LIST.GAME_RULE = "GAME_RULE"
VIEW_LIST.RECHARGE_RIGHT_NOW = "RECHARGE_RIGHT_NOW"
VIEW_LIST.ROATEWAIT_LAYER = "ROATEWAIT_LAYER"
VIEW_LIST.SELECT_LINK_LAYER = "SELECT_LINK_LAYER"
VIEW_LIST.HALL_MESSAGE_LAYER = "HALL_MESSAGE_LAYER"
VIEW_LIST.BANK_MODIFY_LAYER = "BANK_MODIFY_LAYER"
